# ==============================================================================
# Face Recognition REST API Engine - Configuration
# Note: Values here can be overridden by environment variables in .env
# ==============================================================================

[MYSQL_DB_NAME]
DB_NAME = cairo_face_recognition

[PROTOTEXT_FILE_PATH]
PROTOTEXT_FILE = ./Detection/FRS_MODEL/deploy_prototext.txt

[RESNET_MODEL_PATH]
RESNET_MODEL = ./Detection/FRS_MODEL/face_caffe_model

[THRESHOLD]
MIN_THRESHOLD = 0.35
